# This file contains default values, and does not need to be edited. All
# important settings can be changed from the admin interface.

defaults: &defaults
  site_title: Sauti
  site_short_description: 'YouthVoices civic platform advancing democratic principles'
  site_description: 'Sauti advances democratic principles by blending social timelines, civic forums, and advisory polling for Kenyan youth.'
  site_extended_description: 'Sauti is the YouthVoices fork of Mastodon—a civic platform advancing democratic principles through county-to-national discussion spaces, live civic rooms, and transparent advisory polling.'
  site_terms: ''
  site_contact_username: ''
  site_contact_email: ''
  registrations_mode: 'none'
  profile_directory: true
  closed_registrations_message: ''
  local_live_feed_access: 'public'
  remote_live_feed_access: 'public'
  local_topic_feed_access: 'public'
  remote_topic_feed_access: 'public'
  show_staff_badge: true
  preview_sensitive_media: false
  noindex: false
  theme: 'system'
  trends: true
  trends_as_landing_page: true
  trendable_by_default: false
  disallowed_hashtags: # space separated string or list of hashtags without the hash
  bootstrap_timeline_accounts: ''
  activity_api_enabled: true
  peers_api_enabled: true
  show_domain_blocks: 'disabled'
  show_domain_blocks_rationale: 'disabled'
  require_invite_text: false
  backups_retention_period: 7
  captcha_enabled: false
  allow_referrer_origin: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
